---
title: "Research"
toc: false
anchor-sections: false
---

My research broadly explores how the intersections of poverty governance and neighborhood change impact placemaking in urban spaces. To investigate such questions, I employ a mixed-methods approach that combines spatiotemporal analysis with field observations and ethnography. My projects are organized by the following substantive areas:


#### ***Governance of Homelessness***
---

These studies focus on how cities manage homelessness through various practices of social control, punishment, and care.

<details>

<summary>"Policing Homelessness: Neighborhood Predictors of Clearing Encampments and Vehicle Residents"</summary>

<p>

> My [Master's Thesis](https://www.proquest.com/dissertations-theses/policing-homelessness-enforcing-neighborhood/docview/3230341302/se-2){target="_blank"} examines the relationship between neighborhood characteristics and forced displacement of unsheltered residents in Seattle, WA. I find that the prevalence of homelessness in an area may not substantially influence policing interventions. Removal instead seems related to other contextual factors. Most notably, increases in neighborhood property value predict more encampment sweeps and vehicle impoundments. Both interventions also positively correlate with public complaints and crime. These findings largely support past theories on development-driven and complaint-oriented policing.
>
> *Social Problems* recently accepted the article for publication (likely in spring 2026). I also presented this work at the following conferences: American Sociological Association; American Society of Criminology; and International Society for Justice Research.

<p>

</details>

<details>

<summary>"Forced Displacement of People Experiencing Homelessness: Housing and Movement Outcomes after Encampment Clearances"</summary>

<p>

> This study evaluates people's housing outcomes and movement patterns following encampment clearances in Seattle, WA. We find that displaced residents do not travel far, yet clearances may still reduce visible homelessness by reducing the size of camp communities. Furthermore, people appear unlikely to move indoors and instead face high risks of losing contact with service providers - regardless of individual demographics. These results corroborate broader literature on place attachments, residential mobility, and invisibilization of poverty.
>
> We presented this work at the Western Society of Criminology conference. The paper was accepted for presentation at the upcoming Population Association of America meeting. Other authors include Zack W. Almquist, Amy Hagopian, and Kim Serry.

<p>

</details>

<details>

<summary>"Salud Callejera: Mobilizing Cuidado at the Margins of Neoliberalism; Reimagining Care for People Experiencing Homelessness in Buenos Aires"</summary>

<p>

> Based in Buenos Aires, Argentina, my undergraduate [Honors Thesis](https://digitalcommons.bowdoin.edu/honorsprojects/113/){target="_blank"} analyzes care for people experiencing homelessness as a site for both reproducing and resisting neoliberal governance. This study finds that municipal services and the public health system render individuals responsible for housing insecurity by medicalizing poverty as a symptom of psychosocial illness. As an alternative, civil society networks reimagine care as a collective right and site of political mobilization. In addition to field observations, I draw upon interviews with people experiencing or at risk of homelessness, members of civil society organizations, public health providers, and municipal social workers.
>
> I presented this work at the Society for Latin American and Caribbean Anthropology Conference in 2019. The paper also won a departmental award for best senior thesis.

<p>

</details>

<details>

<summary>"Salud callejera: La Atenci칩n Primaria de Salud en los m치rgenes de la Ciudad de Buenos Aires: Redes de cuidado de una organizaci칩n de la Sociedad Civil para personas en situaci칩n de calle"</summary>

<p>

> This undergraduate [study](https://digitalcollections.sit.edu/isp_collection/2769/){target="_blank"} examines how civil society networks facilitate access to primary care for people experiencing homelessness in Buenos Aires, Argentina. Drawing upon interviews and field observations, I also explore how care differs across state services, civil society networks, and peer groups.

<p>

</details>

I have additionally worked with Dr. Nathalie Williams, Dr. Jerald Herting, and other UW students to pioneer a [panel survey](https://sites.uw.edu/pugetsounddata/){target="_blank"} of the unhoused population in Washington's Puget Sound region. Our team recently produced a [report](https://soc.washington.edu/sites/soc/files/documents/A%20Portrait%20of%20Unhoused%20Seattle-%209-16-25.pdf){target="_blank"} based on pilot data collection. We also conducted focus groups with unsheltered participants to explore how to build effective and ethical longitudinal survey strategies. Our findings are currently under review for publication.

#### ***Disorder in Public Spaces***

---

Sound Transit (ST) and the UW Department of Sociology are currently conducting a project examining the causes, patterns, and consequences of social disorder within the local light rail system. As a research assistant for Dr. Kyle Crowder and Dr. Charles Lanfear, I have helped conduct a literature review, design study protocols, and collect preliminary data through systematic social observation and urban-ecological mapping. I have also aided Dr. Nathalie Williams and other colleagues with developing a panel survey to assess the transit perceptions and behaviors of the general Puget Sound population. My role has further involved supervising undergraduate students to pilot our study. We plan to begin collecting data in spring 2026.

#### ***Housing Markets and Inequality***
---

I recently assisted Dr. Drew Messamore with compiling tax parcel records and business data to explore trends in rental housing dynamics across the Puget Sound. We plan to examine the consequences of changing ownership patterns on housing affordability and urban inequality.

<div style="height: 0.5em;"></div>

### **Professional Experience**

Please see other relevant professional experience below:

-   **Independent Researcher**, Washington State Center for Court Research \| *2024*

    <details>

    <summary>"Legal Financial Obligations in Washington's Courts"</summary>

    <p>

    I helped write a [legislative report](https://www.courts.wa.gov/subsite/wsccr/docs/LFO%20WSCCR%20Report%20-%20Published.pdf){target="_blank"} examining legal financial obligations across Washington courts. The project involved quantitative and text data analysis, stakeholder engagement, and writing for public audiences.

    <p>

    </details>

-   **Thomas J. Watson Fellow**, Watson Foundation \| *2019-2020*

    <details>

    <summary>"The Street Retold: Stories of Homeless Community Empowerment"</summary>

    <p>

    This international [project](https://fellows.watson.foundation/51/fellows/brandon-morande.html){target="_blank"} explores how peer-based initiatives empower people confronting homelessness to share experiences, develop solidarity, and help one another survive the streets. I also examine how these communities occupy often inaccessible spaces to change perceptions of homelessness. I documented my observations and interviewees' stories on Instagram, [\@thestreetretold](https://www.instagram.com/thestreetretold/){target="_blank"}.

    <p>

    </details>


---

Please read this 2025 [newsletter](https://soc.washington.edu/news/2025/02/18/brandon-morandes-research-examines-intersections-between-punishment-poverty-and) by the UW Department of Sociology for more details about my graduate research. You can also find further information about my undergraduate work and Watson Fellowship in this [article](https://www.bowdoin.edu/news/2019/04/after-reaching-out-to-the-homeless-a-senior-discovers-how-they-help-themselves.html){target="_blank"} by Bowdoin College.
